"""adding nullable values

Revision ID: 0b2b25e7b85d
Revises: 697f0c414165
Create Date: 2025-11-22 08:26:12.394777

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b2b25e7b85d"
down_revision: Union[str, Sequence[str], None] = "697f0c414165"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "msg_urls", "message_text", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "msg_urls", "expired_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "msg_urls", "expired_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "msg_urls", "message_text", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
