"""added nullable value for filename

Revision ID: 3bb924b3bd0c
Revises: 109c95dfe118
Create Date: 2025-11-28 21:44:29.291585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb924b3bd0c'
down_revision: Union[str, Sequence[str], None] = '109c95dfe118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('msg_files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('msg_files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
