"""creating tables

Revision ID: 697f0c414165
Revises: e64f00607ba3
Create Date: 2025-11-22 07:05:37.938159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697f0c414165'
down_revision: Union[str, Sequence[str], None] = 'e64f00607ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_urls',
    sa.Column('url_code', sa.String(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('url_code')
    )
    op.create_table('msg_files',
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('url_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['url_code'], ['msg_urls.url_code'], ),
    sa.PrimaryKeyConstraint('filepath')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msg_files')
    op.drop_table('msg_urls')
    # ### end Alembic commands ###
